# Generated by Django 5.0.2 on 2024-08-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_caregiver_job_scheduled_time_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accepted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='proposed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
