# Generated by Django 4.2.10 on 2024-09-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('view_deleted_job', 'Can view deleted job')]},
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Respite Care', 'Respite Care'), ('Home Care', 'Home Care'), ('Senior Care', 'Senior Care'), ('Child Care', 'Child Care'), ('Disability Care', 'Disability Care'), ('Palliative Care', 'Palliative Care'), ('Post-Surgical Care', 'Post-Surgical Care'), ('Maternity Care', 'Maternity Care'), ('Dementia Care', 'Dementia Care')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Declined', 'Declined'), ('Deleted', 'Deleted')], default='Open', max_length=50),
        ),
    ]
