# Generated by Django 5.0.2 on 2024-09-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_dispute_assigned_moderator_dispute_resolved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=50),
        ),
    ]
