# Generated by Django 4.2.10 on 2024-09-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
