# Generated by Django 4.2.10 on 2024-09-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_experiencecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencecategory',
            name='job_type',
            field=models.CharField(choices=[('Respite Care', 'Respite Care'), ('Home Care', 'Home Care'), ('Senior Care', 'Senior Care'), ('Child Care', 'Child Care'), ('Disability Care', 'Disability Care'), ('Palliative Care', 'Palliative Care'), ('Post-Surgical Care', 'Post-Surgical Care'), ('Maternity Care', 'Maternity Care'), ('Dementia Care', 'Dementia Care')], default=222, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiencecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
