# Generated by Django 5.0.2 on 2024-10-01 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_customuser_certifications_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='document_type',
            field=models.CharField(default=55, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
