# Generated by Django 5.0.2 on 2024-10-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_certification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('Lusaka', 'Lusaka'), ('Ndola', 'Ndola'), ('Kitwe', 'Kitwe'), ('Livingstone', 'Livingstone'), ('Chipata', 'Chipata'), ('Mansa', 'Mansa'), ('Kabwe', 'Kabwe'), ('Solwezi', 'Solwezi')], default='Lusaka', max_length=50),
        ),
    ]
